project_id = "riguxshscsoygimxzwaf"

[functions.create-student]
verify_jwt = false

[functions.delete-student]
verify_jwt = false

[functions.hdfc-create-order]
verify_jwt = false

[functions.hdfc-payment-callback]
verify_jwt = false

[functions.hdfc-create-session]
verify_jwt = false

[functions.hdfc-order-status]
verify_jwt = false

[functions.hdfc-webhook]
verify_jwt = false

[functions.hdfc-refund]
verify_jwt = false

[functions.hdfc-verify-payment]
verify_jwt = false